-- comsocwebapp database schema.
--
-- Portability notes (see database.md):
--   * Only VARCHAR / INTEGER / TIMESTAMP are used.  These three types exist in
--     SQLite, MySQL, MariaDB, PostgreSQL and Oracle.
--   * Booleans are stored as INTEGER 0/1 -- Oracle and older MySQL have no
--     native BOOLEAN, so we never rely on one.
--   * No JSON columns, no arrays, no ENUMs, no dialect-specific UPSERT.
--   * "INTEGER PRIMARY KEY" is the SQLite spelling of an auto-incrementing
--     surrogate key.  On other engines replace it with the local equivalent
--     (SERIAL / BIGSERIAL on PostgreSQL, INTEGER AUTO_INCREMENT on MySQL,
--     NUMBER GENERATED BY DEFAULT AS IDENTITY on Oracle).  This is the *only*
--     line in the whole project that is dialect-dependent; every query issued
--     at runtime is plain ANSI SQL.
--   * DROP TABLE IF EXISTS is supported everywhere except Oracle.

DROP TABLE IF EXISTS execution_logs;
DROP TABLE IF EXISTS preferences;
DROP TABLE IF EXISTS invitations;
DROP TABLE IF EXISTS options;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS users;

-- 1. users -- administrators and participants, real and dummy.
CREATE TABLE users (
    id            INTEGER PRIMARY KEY,
    email         VARCHAR(255),
    password_hash VARCHAR(255),
    is_admin      INTEGER   NOT NULL DEFAULT 0,
    is_dummy      INTEGER   NOT NULL DEFAULT 0,
    created_at    TIMESTAMP
);

-- Email is unique only among real users; dummy users carry NULL emails and
-- most engines allow arbitrarily many NULLs in a UNIQUE index.
CREATE UNIQUE INDEX ux_users_email ON users (email);

-- 2. settings -- one row per social-choice problem instance.
CREATE TABLE settings (
    id           INTEGER PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    pref_format  VARCHAR(50)  NOT NULL,
    status       VARCHAR(50)  NOT NULL DEFAULT 'draft',
    budget_limit INTEGER      NOT NULL DEFAULT 0
);

-- 3. options -- items, candidates or projects belonging to a setting.
CREATE TABLE options (
    id          INTEGER PRIMARY KEY,
    setting_id  INTEGER      NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    cost        INTEGER      NOT NULL DEFAULT 0,
    FOREIGN KEY (setting_id) REFERENCES settings (id)
);

CREATE INDEX ix_options_setting ON options (setting_id);

-- 4. invitations -- access-control tokens.
CREATE TABLE invitations (
    id         INTEGER PRIMARY KEY,
    setting_id INTEGER      NOT NULL,
    token      VARCHAR(255) NOT NULL,
    is_generic INTEGER      NOT NULL DEFAULT 0,
    is_used    INTEGER      NOT NULL DEFAULT 0,
    FOREIGN KEY (setting_id) REFERENCES settings (id)
);

CREATE UNIQUE INDEX ux_invitations_token ON invitations (token);

-- 5. preferences -- one row per (user, option) pair.
--    `value` holds a rank (1,2,3...), an approval flag (0/1) or points/currency.
CREATE TABLE preferences (
    id         INTEGER PRIMARY KEY,
    user_id    INTEGER NOT NULL,
    setting_id INTEGER NOT NULL,
    option_id  INTEGER NOT NULL,
    value      INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id)   REFERENCES users (id),
    FOREIGN KEY (setting_id) REFERENCES settings (id),
    FOREIGN KEY (option_id) REFERENCES options (id)
);

-- A user may hold at most one value per option.  The unique index lets the
-- portable "UPDATE, then INSERT if no row was touched" idiom in db.py stand in
-- for a dialect-specific UPSERT.
CREATE UNIQUE INDEX ux_preferences_ballot ON preferences (user_id, option_id);
CREATE INDEX ix_preferences_setting ON preferences (setting_id);

-- 6. execution_logs -- results of running a rule.
CREATE TABLE execution_logs (
    id         INTEGER PRIMARY KEY,
    setting_id INTEGER      NOT NULL,
    rule_name  VARCHAR(100) NOT NULL,
    outcome    VARCHAR(4000),
    run_log    VARCHAR(4000),
    FOREIGN KEY (setting_id) REFERENCES settings (id)
);

CREATE INDEX ix_execution_logs_setting ON execution_logs (setting_id);
